### ISSUE TITLE
Publication of Data

### ISSUE THREAD

**Issue by azerbe** [tapilab/is-xhuang1994#4]
Hello,

do you guys have plans to release your labeled twitter accounts?
I'm a student myself and interested in this topic. That would save some people
a bit of time and you could get more responses to your "publication" and validation
of your results.

Kind Regards

**Comment by aronwc** [comment]
Hi @azerbe,
Thanks for your interest. We should be able to share the data soon. 
In the meantime, I recommend checking out this repository:
https://botometer.iuni.iu.edu/bot-repository/

**Comment by azerbe** [comment]
Thanks. I know these Datasets (and the papers) allready. But like you, I found out that the honeypot approach is biased and can't be used to train a good (generializeable) model.

More data is never bad and I'm kinda lazy when it comes to such repetitive tasks like labeling twitter accounts by hand. ;-)

**Comment by xhuang1994** [comment]
@azerbe Hi, I just saw the email from Dr. Culotta but I can't reply to him (says account doesn't exist). I do have data of about 500 users that I manually labeled. The data will be in a MongoDB database instance if it's OK.

**Comment by xhuang1994** [comment]
But be noted that people may have different definitions of bots and so there could be some inconsistency in identifying them. I slightly changed my rule for labeling several times during the process. Also I have showed Dr. Culotta that some bots really cannot be labeled.

**Comment by aronwc** [comment]
@xhuang1994 Which email did you try? Feel free to email me at my iit address.

**Comment by xhuang1994** [comment]
I tried to reply to A-Culotta@neiu.edu and it says no such account.
I just sent my data from 2258921574@qq.com to your aculotta@iit.edu. I'll paste my comment here:

Attached please find the link to my data. Use 
mongorestore --archive=new_users.archive --db YOURDB --collection YOURCOLLECTION 
to load the data (be careful not to overwrite your own data). 

I manually labeled about 500 users, whose labels are 1 for humans and 0 for bots. For each user I collected its number of followers & number of followings hourly:

Do not use the variables 
"followers_count_record" and 
"followings_count_record" since I didn't include a time stamp with the numbers. 

Use 
"followers_count_record_new" and 
"followings_count_record_new" instead. 

The first number is the count and the second to the fifth are month, day, hour, minute, respectively. I think most other variables' names explain themselves. If you have any question just reply to this email address.

**Comment by aronwc** [comment]
@xhuang1994 didn't receive it. Can you email me directly to discuss rather than here?

**Comment by xhuang1994** [comment]
@aronwc I had my friend email it to you. You should've received it. Above was some comment for my data FYI.

**Comment by azerbe** [comment]
Thanks for you're replies. But I have no connection to @aronwc . :-)
Would be kind if you can email me the data to azerbe@students.uni-mainz.de .

Thanks in advance!

**Comment by aronwc** [comment]
@xhuang1994 I haven't received any emails.

**Comment by xhuang1994** [comment]
I've had my friend email it to both of you, @aronwc last night, and @azerbe this morning, respectively. He's using @126.com or @163.com email address. Please double check your inbox and spam folder.

**Comment by aronwc** [comment]
Nope.

**Comment by azerbe** [comment]
I received the mail. Thanks.

**Comment by xhuang1994** [comment]
Glad to hear that! Any further questions please email me at hx1994126@126.com
